/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#fff8f4',
          dim: '#dfd9d5',
          bright: '#fff8f4',
        },
        'surface-container': {
          lowest: '#ffffff',
          low: '#f9f2ee',
          DEFAULT: '#f3ede9',
          high: '#eee7e3',
          highest: '#e8e1dd',
        },
        'on-surface': {
          DEFAULT: '#1d1b19',
          variant: '#534248',
        },
        'inverse-surface': '#33302d',
        'inverse-on-surface': '#f6efeb',
        outline: {
          DEFAULT: '#867278',
          variant: '#d8c0c7',
        },
        'surface-tint': '#993e68',
        primary: {
          DEFAULT: '#993e68',
          foreground: '#ffffff',
          container: '#ff92bf',
          'on-container': '#7a264f',
        },
        secondary: {
          DEFAULT: '#4b626d',
          foreground: '#ffffff',
          container: '#cde6f3',
          'on-container': '#516873',
        },
        tertiary: {
          DEFAULT: '#62597b',
          foreground: '#ffffff',
          container: '#b9aed4',
          'on-container': '#494161',
        },
        error: {
          DEFAULT: '#ba1a1a',
          foreground: '#ffffff',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        'primary-fixed': '#ffd9e5',
        'primary-fixed-dim': '#ffb0ce',
        'on-primary-fixed': '#3e0022',
        'on-primary-fixed-variant': '#7b2750',
        'secondary-fixed': '#cde6f3',
        'secondary-fixed-dim': '#b2cad7',
        'on-secondary-fixed': '#051e28',
        'on-secondary-fixed-variant': '#334a54',
        'tertiary-fixed': '#e8ddff',
        'tertiary-fixed-dim': '#ccc1e8',
        'on-tertiary-fixed': '#1e1734',
        'on-tertiary-fixed-variant': '#4a4262',
        'surface-variant': '#e8e1dd',
        background: '#fff8f4',
        'on-background': '#1d1b19',
        cream: '#FFF8F4',
        'bubblegum-pink': '#FF92BF',
        'baby-blue': '#D9F2FF',
        lavender: '#E8DDFF',
        mint: '#D4F8E8',
        'butter-yellow': '#FFF4CC',
        peach: '#FFD9CC',
        charcoal: '#5D5754',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        pixel: ['"Pixelify Sans"', 'monospace'],
        fredoka: ['Fredoka', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'window-margin': '20px',
        'gutter': '16px',
      },
      borderRadius: {
        xl: "1.5rem",
        lg: "1rem",
        md: "0.75rem",
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        full: "9999px",
      },
      boxShadow: {
        'ghost': '4px 4px 0px 0px rgba(93, 87, 84, 0.1)',
        'ghost-hover': '6px 6px 0px 0px rgba(93, 87, 84, 0.15)',
        'ghost-pressed': '0px 0px 0px 0px rgba(93, 87, 84, 0)',
        'pixel': '4px 4px 0px 0px rgba(93, 87, 84, 0.1)',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '0.02em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '0.05em' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        sparkle: {
          '0%, 100%': { opacity: '0.5', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.2)' },
        },
        blink: {
          '0%, 90%, 100%': { opacity: '1' },
          '95%': { opacity: '0' },
        },
        drift: {
          '0%': { transform: 'translateX(-10%)' },
          '100%': { transform: 'translateX(110%)' },
        },
        fadeScale: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { transform: 'scale(1.2)', opacity: '1' },
          '100%': { transform: 'scale(0.5)', opacity: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        float: 'float 3s ease-in-out infinite',
        sparkle: 'sparkle 2s infinite ease-in-out',
        blink: 'blink 4s infinite',
        drift: 'drift 20s linear infinite',
        fadeScale: 'fadeScale 0.5s forwards',
        shimmer: 'shimmer 2s linear infinite',
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
